apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cluster.id }}-elasticsearch-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: elasticsearch
    statefulset-name: {{ .Values.cluster.id }}-nodes
data:
  elasticsearch.yml: |+
    cluster.name: {{ .Values.cluster.name }}
    network.host: 0.0.0.0
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    http.cors.allow-headers: "*"
    bootstrap.system_call_filter: false
    xpack.security.enabled: false