apiVersion: v1
kind: Service
metadata:
  name: es-{{ .Values.cluster.id }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.cluster.id }}
    app.kubernetes.io/name: elasticsearch
    statefulset-name: {{ .Values.cluster.id }}-nodes
spec:
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app.kubernetes.io/instance: {{ .Values.cluster.id }}
    app.kubernetes.io/name: elasticsearch
    statefulset-name: {{ .Values.cluster.id }}-nodes
  sessionAffinity: None
  type: ClusterIP