apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.cluster.id }}
    app.kubernetes.io/name: elasticsearch
    statefulset-name: {{ .Values.cluster.id }}-nodes
  name: {{ .Values.cluster.id }}-nodes
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: 1  # 设置 maxUnavailable 为 1，表示在维护期间最多只允许一个 Pod 离线
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/instance: {{ .Values.cluster.id }}
      statefulset-name: {{ .Values.cluster.id }}-nodes