apiVersion: v1
data:
  elasticsearch.yml: |
    cluster.initial_master_nodes:
      - {{ .Values.cluster.id }}-masters-0
      - {{ .Values.cluster.id }}-masters-1
      - {{ .Values.cluster.id }}-masters-2
    cluster.name: test
    discovery.seed_providers: file
    discovery.seed_resolver.timeout: 20s
    discovery.zen.fd.ping_interval: 10s
    discovery.zen.fd.ping_retries: "10"
    discovery.zen.fd.ping_timeout: 30s
    discovery.zen.ping_timeout: 10s
    network.bind_host: 0.0.0.0
    network.publish_host: ${POD_IP}
    node.attr.rack_id: ${RACK_ID}
    node.attr.zone_id: ${ZONE_ID}
    node.data: true
    node.master: false
    node.name: ${POD_NAME}
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.cluster.id }}
    app.kubernetes.io/name: elasticsearch
  name: {{ .Values.cluster.id }}-node-es-config-yaml
  namespace: {{ .Values.cluster.id }}