apiVersion: v1
data:
  installPlugins.sh: ""
  plugins-config-map: |-
    analysis-icu,http://localhost:8080/plugin/7.10.2/analysis-icu
    analysis-ik,http://localhost:8080/plugin/7.10.2/analysis-ik
    analysis-phonetic,http://localhost:8080/plugin/7.10.2/analysis-phonetic
    analysis-pinyin,http://localhost:8080/plugin/7.10.2/analysis-pinyin
    analysis-stconvert,http://localhost:8080/plugin/7.10.2/analysis-stconvert
    ingest-attachment,http://localhost:8080/plugin/7.10.2/ingest-attachment
    repository-s3,http://localhost:8080/plugin/7.10.2/repository-s3
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.cluster.id }}
    app.kubernetes.io/name: elasticsearch
  name: {{ .Values.cluster.id }}-plugins-config-map
