apiVersion: v1
data:
  es-startup-fs.sh: ""
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.cluster.id }}
    app.kubernetes.io/name: elasticsearch
  name: {{ .Values.cluster.id }}-script