apiVersion: v1
data:
  unicast_hosts.txt: |-
    {{ .Values.cluster.id }}-masters-0.{{ .Values.cluster.id }}-masters.xx-es
    {{ .Values.cluster.id }}-masters-1.{{ .Values.cluster.id }}-masters.xx-es
    {{ .Values.cluster.id }}-masters-2.{{ .Values.cluster.id }}-masters.xx-es
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.cluster.id }}
    app.kubernetes.io/name: elasticsearch
  name: {{ .Values.cluster.id }}-nodes-unicast-hosts