apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.cluster.id }}
    app.kubernetes.io/name: elasticsearch
  name: {{ .Values.cluster.id }}-kibana
  namespace: {{ .Values.cluster.id }}
spec:
  clusterIP: None
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    statefulset-name: {{ .Values.cluster.id }}-kibana
  sessionAffinity: None
  type: ClusterIP