{{- if .Values.docker -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-image-secret
  namespace: {{ .Release.Namespace }}
  labels:
    "app.kubernetes.io/instance": {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  {{- with .Values.docker }}
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .registry (print .username ":" .password | b64enc) | b64enc }}
  {{- end }}
{{- end -}}