{{- if .Values.rbac.isCreate }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Release.Name}}-manager-rolebinding
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.Release.Name}}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{.Values.operatorConfig.releaseName}}-sa
    namespace:  {{ .Values.operatorConfig.namespace }}
{{- end }}